# Generated by Django 5.1.1 on 2024-09-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_rename_clothes_clothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='clothes_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='clothes_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='clothes_title',
            field=models.CharField(max_length=250),
        ),
    ]
